name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10
    - name: Scalafmt
      run: sbt scalafmtCheck
    - name: Scalafix
      run: sbt 'scalafixAll --check'
    - name: Test
      run: sbt test
