name: Publish
on:
  release:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Coursier cache
      uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        jvm: adopt:8
        apps: sbt scala
    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sbt sonatypeBundleRelease
